paddle:
  prices:
    individual-monthly: pri_01kqygmqdz5ccsw3k6kbmwvng1
    individual-annual: pri_01kqygs0gfff3cqstx9z86nmdm
    individual-ai-monthly: pri_01kqygr2c83f7e2r050xn6n0ap
    individual-ai-annual: pri_01kqygvj1nrwk8wx707f35ascn
