server:
  port: 8083

spring:
  application:
    name: authorize-net-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

authnet:
  api-login-id: ${AUTHNET_API_LOGIN_ID}
  transaction-key: ${AUTHNET_TRANSACTION_KEY}
  environment: ${AUTHNET_ENV}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      gatewayCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-calls-in-half-open-state: 3
  retry:
    instances:
      gatewayRetry:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.io.IOException
          - java.net.ConnectException
